from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox

import requests

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(668, 310)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("application-x-executable")
        MainWindow.setWindowIcon(icon)
        MainWindow.setAnimated(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.search_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.search_btn.setGeometry(QtCore.QRect(10, 270, 121, 31))
        self.search_btn.setObjectName("search_btn")
        self.search_btn.clicked.connect(self.preencherCampos)
        self.clean_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clean_btn.setGeometry(QtCore.QRect(570, 270, 91, 31))
        self.clean_btn.setObjectName("clean_btn")
        self.clean_btn.clicked.connect(self.clearFields)
        self.cnpj_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.cnpj_label.setGeometry(QtCore.QRect(200, 0, 141, 21))
        self.cnpj_label.setObjectName("cnpj_label")
        self.cnpj_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.cnpj_edit.setGeometry(QtCore.QRect(200, 20, 151, 31))
        self.cnpj_edit.setObjectName("cnpj_edit")
        self.cnpj_edit.setInputMask('99.999.999/9999-99')
        self.razao_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.razao_edit.setGeometry(QtCore.QRect(10, 70, 421, 31))
        self.razao_edit.setObjectName("razao_edit")
        self.fantasia_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.fantasia_edit.setGeometry(QtCore.QRect(470, 70, 191, 31))
        self.fantasia_edit.setObjectName("fantasia_edit")
        self.fantasia_edit.setReadOnly(True)
        self.endereco_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.endereco_edit.setGeometry(QtCore.QRect(10, 120, 461, 31))
        self.endereco_edit.setObjectName("endereco_edit")
        self.num_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.num_edit.setGeometry(QtCore.QRect(590, 120, 71, 31))
        self.num_edit.setObjectName("num_edit")
        self.bairro_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.bairro_edit.setGeometry(QtCore.QRect(10, 170, 301, 31))
        self.bairro_edit.setObjectName("bairro_edit")
        self.cidade_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.cidade_edit.setGeometry(QtCore.QRect(420, 170, 241, 31))
        self.cidade_edit.setObjectName("cidade_edit")
        self.uf_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.uf_edit.setGeometry(QtCore.QRect(10, 220, 41, 31))
        self.uf_edit.setObjectName("uf_edit")
        self.cep_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.cep_edit.setGeometry(QtCore.QRect(130, 220, 131, 31))
        self.cep_edit.setObjectName("cep_edit")
        self.email_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.email_edit.setGeometry(QtCore.QRect(420, 220, 241, 31))
        self.email_edit.setObjectName("email_edit")
        self.razao_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.razao_label.setGeometry(QtCore.QRect(10, 50, 111, 16))
        self.razao_label.setObjectName("razao_label")
        self.fantasia_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.fantasia_label.setGeometry(QtCore.QRect(470, 50, 141, 16))
        self.fantasia_label.setObjectName("fantasia_label")
        self.endereco_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.endereco_label.setGeometry(QtCore.QRect(10, 100, 61, 16))
        self.endereco_label.setObjectName("endereco_label")
        self.num_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.num_label.setGeometry(QtCore.QRect(590, 100, 51, 16))
        self.num_label.setObjectName("num_label")
        self.bairro_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.bairro_label.setGeometry(QtCore.QRect(10, 150, 61, 16))
        self.bairro_label.setObjectName("bairro_label")
        self.cidade_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.cidade_label.setGeometry(QtCore.QRect(420, 150, 61, 16))
        self.cidade_label.setObjectName("cidade_label")
        self.uf_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.uf_label.setGeometry(QtCore.QRect(10, 200, 21, 16))
        self.uf_label.setObjectName("uf_label")
        self.cep_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.cep_label.setGeometry(QtCore.QRect(120, 200, 31, 16))
        self.cep_label.setObjectName("cep_label")
        self.email_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.email_label.setGeometry(QtCore.QRect(420, 200, 41, 16))
        self.email_label.setObjectName("email_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.razao_edit.setReadOnly(True)
        self.endereco_edit.setReadOnly(True)
        self.num_edit.setReadOnly(True)
        self.bairro_edit.setReadOnly(True)
        self.cidade_edit.setReadOnly(True)
        self.uf_edit.setReadOnly(True)
        self.cep_edit.setReadOnly(True)
        self.email_edit.setReadOnly(True)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Consulta de CNPJ"))
        self.search_btn.setText(_translate("MainWindow", "Consultar"))
        self.clean_btn.setText(_translate("MainWindow", "Limpar"))
        self.cnpj_label.setText(_translate("MainWindow", "Insira o CNPJ:"))
        self.razao_label.setText(_translate("MainWindow", "Nome/Razão social"))
        self.fantasia_label.setText(_translate("MainWindow", "Nome fantasia/Apelido"))
        self.endereco_label.setText(_translate("MainWindow", "Endereço"))
        self.num_label.setText(_translate("MainWindow", "Número"))
        self.bairro_label.setText(_translate("MainWindow", "Bairro"))
        self.cidade_label.setText(_translate("MainWindow", "Cidade"))
        self.uf_label.setText(_translate("MainWindow", "UF"))
        self.cep_label.setText(_translate("MainWindow", "CEP"))
        self.email_label.setText(_translate("MainWindow", "E-mail"))
    
    def clearFields(self):
        self.cnpj_edit.clear()
        self.cep_edit.clear()
        self.email_edit.clear()
        self.uf_edit.clear()
        self.razao_edit.clear()
        self.fantasia_edit.clear()
        self.endereco_edit.clear()
        self.num_edit.clear()
        self.bairro_edit.clear()
        self.cidade_edit.clear()

    def preencherCampos(self):
        badchars = ['.', '/', '-']
        ncnpj = "".join(i for i in self.cnpj_edit.text() if not i in badchars)
        if len(ncnpj) == 0:
            QMessageBox.warning(MainWindow, 'Aviso', 'Digite o CNPJ!')
        else:            
            getreq = requests.api.get(f'https://receitaws.com.br/v1/cnpj/{ncnpj}')
            cnpj = getreq.json()
            try:
                razaosocial = cnpj['nome']
                nomefantasia = cnpj['fantasia']
                endereco = cnpj['logradouro']
                numero = cnpj['numero']
                cidade = cnpj['municipio']
                uf = cnpj['uf']
                cep = cnpj['cep']
                bairro = cnpj['bairro']
                email = cnpj['email']
                self.razao_edit.setText(razaosocial)
                self.fantasia_edit.setText(nomefantasia)
                self.endereco_edit.setText(endereco)
                self.num_edit.setText(numero)
                self.cidade_edit.setText(cidade)
                self.uf_edit.setText(uf)
                self.cep_edit.setText(cep)
                self.bairro_edit.setText(bairro)
                self.email_edit.setText(email)
            except Exception:
                QMessageBox.critical(MainWindow, 'Erro', 'CNPJ Inválido!')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    MainWindow.setWindowFlags(QtCore.Qt.WindowType.CustomizeWindowHint | QtCore.Qt.WindowType.WindowCloseButtonHint | QtCore.Qt.WindowType.WindowMinimizeButtonHint)
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
